### ISSUE TITLE
Generate Output Sequence and save it to a MIDI file Error

### ISSUE THREAD

**Issue by Doken-Tokuyama** [asigalov61/Amazing-GPT2-Piano#5]
Hi

Five days ago worked well but today when I generate a midi get this error:

<img width="2046" alt="Captura de pantalla 2020-08-22 a las 4 51 55" src="https://user-images.githubusercontent.com/6333197/90947074-55131380-e433-11ea-8ffa-2bea26502401.png">

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:61: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
100%
3968/3968 [00:34<00:00, 115.93it/s]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

(1, 4096)
Successfully exported the output to output_file.mid
Downloading output_file.mid
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-492ae68ee499>", line 196, in <module>
    files.download('/content/output-midis/output_file.mid')
  File "/usr/local/lib/python3.6/dist-packages/google/colab/files.py", line 143, in download
    raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
FileNotFoundError: Cannot find file: /content/output-midis/output_file.mid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/tensorflow-1.15.2/python3.6/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/tensorflow-1.15.2/python3.6/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.estimator'
---------------------------------------------------------------------------

**Comment by asigalov61** [comment]
Hey there. Sorry I missed your Issue request. I am old and I am new to GitHub so I am still getting used to the navigation and all that stuff :))))

I will check it out and let you know. I wanted to update it but because there is no proper MIDI pre-processor and encoder, I sorta have been putting it off for now.

I actually do not recommend to use GPT2 because it is not specifically designed for Music. And because there is no code/implementations available to make it work well with the music. If you like to help, I would be very happy but its very difficult task considering the complexity so it's ok if you can't do it :)

Meanwhile, please check out my Super Piano 3. This is designed specifically for music and I have a great implementation of it in my repo.

Thank you and I will update as soon as I fix the Colab. Sorry again for late reply :)

**Comment by asigalov61** [comment]
Ok. It is fixed and seem to be working fine. I think I still need to add a player to it cuz the old one did not work. But at least now it works much better and faster, as well as it has a very nice piano-roll now from my Super Piano colabs :)

Enjoy and have fun :)

Please let me know of any other issues/problems so that I can fix it :)

Thanks a lot.
